### ISSUE TITLE
ChildRef tests are failing

### ISSUE THREAD

**Issue by vertexclique** [bastion-rs/bastion#242]
```
---- src/bastion.rs - bastion::Bastion (line 29) stdout ----
Test executable failed (exit code 101).

---- src/child_ref.rs - child_ref::ChildRef::stop (line 225) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'Couldn't send the message.: ()', src/child_ref.rs:10:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


---- src/child_ref.rs - child_ref::ChildRef::kill (line 253) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'Couldn't send the message.: ()', src/child_ref.rs:10:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace



failures:
    src/bastion.rs - bastion::Bastion (line 29)
    src/child_ref.rs - child_ref::ChildRef::kill (line 253)
    src/child_ref.rs - child_ref::ChildRef::stop (line 225)
```

**Comment by o0Ignition0o** [comment]
Might have to do with unfortunate timing while setting up and tearing down bastion, have a look at https://github.com/bastion-rs/bastion/pull/258/files#diff-667612182ac697d0733da0bed8fc9a4dR711 for a workaround when running unit tests

**Comment by o0Ignition0o** [comment]
I think we're good with this one, arent we ?

**Comment by vertexclique** [comment]
@o0Ignition0o yes, we have fixed this.
